version: "3.7"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: uwsgi --ini /app/uwsgi.ini
    env_file:
      - .env
    volumes:
    - .:/app
    links:
      - db
    depends_on:
      - db
    ports:
    - 8000:8000

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    volumes:
      - ../db:/var/lib/postgresql
    ports:
    - 5432:5432
    env_file:
      - .envdb